### PR TITLE
change to append instead of create in systemd file / add logrotate

### PR DESCRIPTION
**Pull request by juliusczar**
change to append instead of create in systemd file / add logrotate for aggregated dcos logs

## Description
https://jira.mesosphere.com/projects/DCOS_OSS/issues/DCOS_OSS-1811

## Urgency
- [ ] Blocker 
- [ ] High
- [x] Medium

## Requirements
- Test all commands and procedures. :white_check_mark:
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links. :white_check_mark:
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, and 1.10). :white_check_mark:
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing). :white_check_mark:

### CODE REVIEW

**Comment by jrx** [comment]
I reviewed this and made some changes:
- Remove the `journalctl --vacuum-size=10M` since this complicates debugging and RCAs 
- Added Example config for logrotate
- Stream-lined the filebeat-journald service

**Review by jrx — APPROVED** [review]

**Comment by jrx** [comment]
@adyatlov @fabianbaier Could you take a look, it this is correct now?

**Comment by fabianbaier** [comment]
lgtm

**Review by fabianbaier — APPROVED** [review]

**Comment by jrx** [comment]
I created a new PR against the new dcos docs site:
https://github.com/mesosphere/dcos-docs-site/pull/442

**Pull request closed without merging**
