### PR TITLE
fix

### PR DESCRIPTION
**Pull request by joel-hamill**

### CODE REVIEW

**Comment by mhausenblas** [comment]
Thanks! @joel-hamill can you pls fix `/api/v1/health/` -> `/system/health/v1/` in all places? Found it at least once more in said document.

**Comment by joel-hamill** [comment]
@mhausenblas a specific location would be helpful.

**Comment by mhausenblas** [comment]
Right below the fix, in https://github.com/dcos/dcos-docs/blob/fix-sys-health-endpoint/1.7/administration/monitoring/index.md#components @joel-hamill

**Comment by joel-hamill** [comment]
@mhausenblas ah, my global search and replace had the a "/" at the end so it missed this one. it's fixed now.

**Comment by mhausenblas** [comment]
Thank you @joel-hamill!

**Pull request merged**
