### PR TITLE
[WIP] Doc site TOC redesign

### PR DESCRIPTION
**Pull request by joel-hamill**
## Description

https://jira.mesosphere.com/browse/DOCS-1827
- redirects https://github.com/dcos/dcos-website/pull/1223

## Urgency
- [ ] Blocker 
- [ ] High
- [x] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

### CODE REVIEW

**Comment by sascala** [comment]
Preliminary comments:
- `Upgrading` looks lonely all by itself. Maybe change `Installing` to `Installing and Upgrading` and put `Upgrade` in that directory? If I understand right, the upgrade and installation processes have a lot of similarities.

- I'd put `API Reference` underneath `Development` -- I'd expect to find reference material all the way at the bottom.

**Comment by karlkfi** [comment]
Do we want `Overview > Architecture` moved to top level?

**Comment by karlkfi** [comment]
I'd rather not have `API Reference` under `Development`. Operators need the API too.

**Comment by sascala** [comment]
I didn't mean in the Development directory. I meant under it in the TOC.

**Comment by karlkfi** [comment]
I agree `Upgrading` looks lonely. It might make sense to have a top level page that talks about "Supported upgrade paths" and then sub-pages for each path: 
- 1.7 -> 1.8
- 1.8 -> 1.9
- 1.9.x -> 1.9.x+1

**Comment by karlkfi** [comment]
Personally, I don't like the top level `Development` category in the TOC. It's ambiguous whether it's development of DC/OS itself or development FOR DC/OS, as in developing packages/services/jobs.

The point of the top level TOC is to avoid users having to make decisions about why type of user they are when all they care about is a specific action they want to perform.

Example use cases (based on questions I've heard on mailing list and slack):
- What does the DC/OS API look like? (search/browse for "api")
- How do I use the DC/OS API look like? (search/browse for "api" or "api usage")
- How do I get logs from services using the API? (search/browse for "logging api" or "service logs")
- How do I create a Universe package? (search/browse for "universe package" or "service package")
- How do I contribute to DC/OS? (search/browse for "contribute" or "development" or "source code")
- How do I extend DC/OS? (search/browse for "plugins" or "modules" or "extending dc/os")
- How do I add a service health check? (search/browse for "health check" or "service health check")
- How do I make the Services GUI show a link to my service? (search/browse for "service link")
- How do I make my service route through Admin Router? (search/browse for "admin router" or "service proxy" or "service link")

Granted, slack/mailing list questions are usually only for this that are currently hard to discover, excluding questions users can already easily find themselves.

Anyway, my point is that everyone who uses DC/OS considers themselves a developer. Having a "development" section doesn't narrow down anything. And if it's "DC/OS Development" or "Service Development", then API is not a subset of that.

**Comment by karlkfi** [comment]
`Administering Clusters` makes me think there's going to be an `Administering Services` section...

**Comment by karlkfi** [comment]
I feel `Service Discovery and Load Balancing` should just be ``Networking` and should include a bunch of networking security topics like:

- Zones & DMZ
- HTTPS, SSL, TLS
    - SSL Termination with HAProxy
    - SSL Termination with AWS ELB (TODO)
    - SSL Termination with Marathon-LB
- Virtual Networking
- Load Balancing and VIPs
- DNS

**Comment by karlkfi** [comment]
Should `Identity and Access Management` just be `Security`? That's the page title... OTOH, "security" is wider than just IAM...

**Comment by karlkfi** [comment]
Top level `Jobs` makes me think there would be a top level `Services`. But I know we avoided `Services` because it was ambiguous with the "Mesosphere Services" and "developing services". Should it instead be `Operating Services` and `Operating Jobs`?

**Comment by joel-hamill** [comment]
@karlkfi @sascala 
- re [lonely upgrade and API reference|https://github.com/dcos/dcos-docs/pull/1020#issuecomment-293974626], i like the change to `Installing and Upgrading DC/OS`
- re [architecture to top-level|https://github.com/dcos/dcos-docs/pull/1020#issuecomment-293975559, what's the reasoning behind making architecture more prominent? i think it fits well logically where it is. 
- re [upgrade fixup|https://github.com/dcos/dcos-docs/pull/1020#issuecomment-293976191], i have filed this JIRA to track this work: https://jira.mesosphere.com/browse/DOCS-1831.
- re [top level Development category|https://github.com/dcos/dcos-docs/pull/1020#issuecomment-293979706], agreed - how about `Developing Services`?
- re [jobs and services|https://github.com/dcos/dcos-docs/pull/1020#issuecomment-294022898], the services topic is currently `Deploying Services and Pods` and i think this makes more sense than `Operating..`. how about `Deploying Jobs`?
-  re [ID and Access to Security|https://github.com/dcos/dcos-docs/pull/1020#issuecomment-294022627] - agreed.
- re [networking section|https://github.com/dcos/dcos-docs/pull/1020#issuecomment-294006652], this does make sense. i have revised with this design.

**Comment by karlkfi** [comment]
re architecture to top-level: I've had complaints that some of the content under architecture is deeper than "overview", but I don't feel super strongly about it. It needs another iteration, I guess, but not now.

**Comment by karlkfi** [comment]
Current:

- Release Notes
- Overview
- Installing and Upgrading
- Metrics
- Administering Clusters
- Security
- Monitoring, Logging, and Debugging
- Deploying Jobs
- Deploying Services and Pods
- Networking
- Storage
- Tutorials
- Developing Services
- API Reference
- Support

1) It feels like `Metrics` is in the wrong place. It should be near logging.
2) Do we need "Pods" called out in the TOC? The ontology is that "services" are either "apps" or "pods". I would prefer the top level page just be `Deploying Services`
3) I would probably put `Deploying Jobs` after/below `Deploying Services`, which I think is more commonly used first.
4) `Tutorials` is most similar to the `Deploying Services` and `Deploying Jobs`. It seems liek those should be closer in ordering.
5) The first few sub-pages in `Administering Clusters` feel like they're not exclusive to 'administration". I would probably recommend moving `GUI` and `CLI` to the top level.
6) `Finding a Public Agent IP` (under `Administering Clusters`) seems like something non-admins might want to do, but I can't really think of a good place to put it.
7) `Accessing the Cluster` definitely sounds like something non-admins would want to do. But `SSHing into Nodes` seems distinctly admin-y. `Accessing the Cluster` also sounds like it overlaps 100% with `Cluster Access` (under `API Reference`). And `Access by Proxy and VPN` (under `Accessing the Cluster`) starts with "When developing services on DC/OS" and " Do not use DC/OS Tunnel in production.". So maybe `Access by Proxy and VPN` should go under `Developing Services`, `SSHing into Nodes` should go directly under `Administering Clusters`, and `Accessing the Cluster`, with it's one sentence, should just be deleted.
8) The `GUI` page feels like it should be multiple pages, organized the same way the GUI is hierarchically.
9) `GUI` and `CLI` seem almost too short... maybe `GUI Reference` and `CLI Reference` or `Command Line Interface (CLI)` and `Graphical User Interface (GUI)`? If they're "references", they might look better near the `API Reference`.

Suggested TOC:

- Release Notes
- Overview
- Installing and Upgrading
- Deploying Jobs
- Deploying Services and Pods
- Tutorials
- Administering Clusters
- Networking
- Security
- Storage
- Metrics
- Monitoring, Logging, and Debugging
- GUI Reference
- CLI Reference
- API Reference
- Developing Services
- Support

**Comment by karlkfi** [comment]
Another option, that kind sorts from admin to user to reference:

Suggested TOC:

- Release Notes
- Overview
- Installing and Upgrading
- Administering Clusters
- Networking
- Security
- Storage
- Metrics
- Monitoring, Logging, and Debugging
- Deploying Jobs
- Deploying Services and Pods
- Tutorials
- GUI Reference
- CLI Reference
- API Reference
- Developing Services
- Support

**Comment by joel-hamill** [comment]
@karlkfi thanks for all the feedback:

1. It feels like Metrics is in the wrong place. It should be near logging.
> agreed, moved metrics
2. Do we need "Pods" called out in the TOC? The ontology is that "services" are either "apps" or "pods". I would prefer the top level page just be Deploying Services 
> agreed, moved pods
3. I would probably put Deploying Jobs after/below Deploying Services, which I think is more commonly used first.
> agreed, moved jobs
4. Tutorials is most similar to the Deploying Services and Deploying Jobs. It seems liek those should be closer in ordering.
 > agreed, moved tutorials
5. The first few sub-pages in Administering Clusters feel like they're not exclusive to 'administration". I would probably recommend moving GUI and CLI to the top level.
> agreed, moved CLI and GUI to top-level headings
6. Finding a Public Agent IP (under Administering Clusters) seems like something non-admins might want to do, but I can't really think of a good place to put it. 
> let's leave as-is for now. most users find things from the search bar anyway (in our docs users tests).
7. Accessing the Cluster definitely sounds like something non-admins would want to do. But SSHing into Nodes seems distinctly admin-y. Accessing the Cluster also sounds like it overlaps 100% with Cluster Access (under API Reference). And Access by Proxy and VPN (under Accessing the Cluster) starts with "When developing services on DC/OS" and " Do not use DC/OS Tunnel in production.". So maybe Access by Proxy and VPN should go under Developing Services, SSHing into Nodes should go directly under Administering Clusters, and Accessing the Cluster, with it's one sentence, should just be deleted.
> good point. i have rearranged TOC accordingly.
8. The GUI page feels like it should be multiple pages, organized the same way the GUI is hierarchically.
> i have filed this JIRA to fixup: https://jira.mesosphere.com/browse/DOCS-1833
9. GUI and CLI seem almost too short... maybe GUI Reference and CLI Reference or Command Line Interface (CLI) and Graphical User Interface (GUI)? If they're "references", they might look better near the API Reference.
> implemented as discussed.

**Comment by joel-hamill** [comment]
@karlkfi here's how my local build appears now 
image

**Comment by karlkfi** [comment]
Should we get a 2nd (or 12th) opinion? Maybe tweet out a pic of the TOC or ask on the user mailing list?

**Comment by joel-hamill** [comment]
@karlkfi we've already gotten positive user feedback on this design, and plenty of negative on the old. i think we should definitely promote it once it is live - and get feedback/iterate that way. i'd rather not involve too many cooks in the kitchen at this point.

**Comment by karlkfi** [comment]
SGTM

**Pull request merged**
