### PR TITLE
Fix link to Paxos.

### PR DESCRIPTION
**Pull request by orsenthil**
## Description

* Reported in Slack.

## Urgency
- [ ] Blocker 
- [ ] High
- [x] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

### CODE REVIEW

**Comment by joerg84** [comment]
LGTM

**Comment by sascala** [comment]
Thanks, @orsenthil and @joerg84 !

**Comment by joel-hamill** [comment]
@orsenthil @sascala the `&#41;` is required for URLs that end in parenthesis. was this not working on dcos.io? was the user looking directly at GitHub? Judith made this (using an another viable escape character): https://github.com/dcos/dcos-docs/pull/931.

**Comment by orsenthil** [comment]
It was not working on dcos.io/docs that's why I raised and fixed. Is the new docs alive to verify the fix?

**Comment by orsenthil** [comment]
I see it fixed now: https://docs.mesosphere.com/1.9/administration/high-availability/

**Pull request merged**
