### PR TITLE
dns-overview: Additional behavior

### PR DESCRIPTION
**Pull request by nlsun**
## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

### CODE REVIEW

**Comment by nlsun** [comment]
Actually hold off on merging this, there may be some changes.

**Comment by joel-hamill** [comment]
@nlsun any update here?

**Comment by sascala** [comment]
@drewkerrigan Would you mind looking this over? Nick Sun made some changes to this document a while back and then mentioned there might be more changes to make... and that's the last we heard about it.

**Comment by drewkerrigan** [comment]
@sascala Just looks like a slight rewording, I don't see the value here and he never informed us of additional changes, so I think we can probably close this unless anyone disagrees.

**Pull request closed without merging**
