### PR TITLE
Backported LIBRPOCESS_PORT doc

### PR DESCRIPTION
**Pull request by joel-hamill**
## Description
- https://jira.mesosphere.com/browse/DOCS-1646
- https://github.com/mesosphere/dcos-docs-enterprise/pull/1054

## Urgency
- [ ] Blocker 
- [ ] High
- [x] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

### CODE REVIEW

**Comment by akaplan-mesosphere** [comment]
LGTM :ship:

**Review by jdef — APPROVED** [review]
Based on my skimming of the dcos configuration generator, this looks right: TIL that LIBPROCESS_PORT is hardcoded for root marathon and metronome on dcos

**Comment by branden** [comment]
@joel-hamill Could you open a PR to update https://github.com/dcos/dcos/blob/master/docs/admin-ports.md with this info as well?

**Review by branden — APPROVED** [review]
:ship:

https://github.com/dcos/dcos/blob/1.8.8/gen/dcos-config.yaml#L485
https://github.com/dcos/dcos/blob/1.8.8/gen/dcos-config.yaml#L502

**Pull request merged**
