### PR TITLE
Ss/marathon tutorial update

### PR DESCRIPTION
**Pull request by sascala**
## What type of changes does your doc introduce?
- [X] Bug fix
- [ ] New feature 

## What is the urgency level of this change?
- [ ] Blocker
- [X] High
- [ ] Medium

## I have completed these items:
- [X] I have tested all commands and code snippets.
- [X] I have built locally and tested for broken links and formatting.
- [X] I have made this change for all affected versions (e.g. 1.7, 1.8, and 1.9).
- [X] My doc follows the style guide: https://github.com/dcos/dcos-docs#contributing.

Ping @emanic @sascala @joel-hamill for reviewing pull request changes.

## If you included a comment with your commit, it appears here:

### CODE REVIEW

**Comment by sascala** [comment]
@joel-hamill This ended up being a fairly significant set of changes. I've checked locally and I'm pretty sure things look good, but I could definitely use another set of eyes.

**Comment by sascala** [comment]
note: this PR is blocked until I can get hello-docs into the Mesosphere DockerHub repository

**Comment by joel-hamill** [comment]
@sascala what's the difference between this and https://github.com/dcos/dcos-docs/pull/683/files ?

**Comment by sascala** [comment]
Yikes I didn't realize you'd reviewed the other (thank you!). I pushed the changes on the wrong branch. This was supposed to just be a branch that makes it clear pods are experimental. So I copied my changes to the appropriate branch and issued the PR.

**Comment by sascala** [comment]
OK, @joel-hamill, I've fixed the mess. This PR incorporates your comments.

**Comment by joel-hamill** [comment]
has anyone outside of docs reviewed this? just want to make sure we've covered the use case.

**Comment by sascala** [comment]
No, I haven't sent it around. I can definitely verify it works, though. Is the issue that it might not be useful to a user? I can send it to someone in support.

**Comment by joel-hamill** [comment]
@sascala yes, just want to make sure it's hitting the target of what a typical user would need. support would be a great option for review.

**Comment by sascala** [comment]
@joel-hamill I chatted with Miguel, who said the containerized public app was similar to the "using marathon-lb" section of the site, but that what I'd written would work well as a "quick start," then the other guide as a more complex implementation. I think I may try to get that change made

**Comment by sascala** [comment]
@joel-hamill I've incorporated Miguel's comments (to move the public containerized app tutorial to the "quick start" section of the marathon-lb topic, then rename the current "quick start" tutorial to imply it's more advanced).

My local build isn't working (currently troubleshooting), but I'd like to finally put this PR to bed. If it looks OK to you, I can check on the testing site before we publish.

**Pull request merged**
