### PR TITLE
Update 1.9 Component Names

### PR DESCRIPTION
**Pull request by karlkfi**
## Description
https://jira.mesosphere.com/browse/DCOS_OSS-600

## Urgency
- [ ] Blocker
- [X] High
- [ ] Medium

### CODE REVIEW

**Comment by joel-hamill** [comment]
@karlkfi LGTM. can you also please make these changes in https://github.com/mesosphere/dcos-docs-enterprise for non-shared topics (e.g. `ports.md` and `configuration-parameters.md`)?

**Comment by joel-hamill** [comment]
Shall I merge?

**Comment by karlkfi** [comment]
Go ahead. Need it merged so I can update the shared pages in enterprise

**Comment by karlkfi** [comment]
Files changed, for reference:

```
$ git --no-pager diff --name-only 135ee422c0bd509c19a6653a8bd4912ab369eece...eec0bf99de372be215ab7d28869328fa8e8f768e
1.9/administration/installing/custom/configuration-parameters.md
1.9/administration/installing/custom/convert-agent-type.md
1.9/administration/installing/custom/troubleshooting.md
1.9/administration/installing/ports.md
1.9/administration/monitoring/nagios.md
1.9/administration/upgrading.md
1.9/overview/architecture/boot-sequence.md
1.9/overview/architecture/components.md
1.9/overview/concepts.md
1.9/overview/design/dns-proxy.md
1.9/overview/design/installation.md
1.9/overview/telemetry.md
1.9/overview/what-is-dcos.md
1.9/usage/jobs/index.md
```

**Comment by karlkfi** [comment]
Comparison with dcos-docs-enterprise

Synched
```
1.9/administration/installing/custom/convert-agent-type.md
1.9/administration/installing/custom/troubleshooting.md
1.9/overview/architecture/boot-sequence.md
1.9/overview/concepts.md
1.9/overview/what-is-dcos.md
1.9/usage/jobs/index.md
```

NOT Synced
```
1.9/administration/installing/custom/configuration-parameters.md
1.9/administration/installing/ports.md
1.9/overview/architecture/components.md
1.9/overview/telemetry.md
```

Not Found!
```
1.9/administration/monitoring/nagios.md
1.9/administration/upgrading.md
1.9/overview/design/dns-proxy.md
1.9/overview/design/installation.md
```

**Pull request merged**
