### PR TITLE
Made criteria consistent across phases.

### PR DESCRIPTION
**Pull request by joerg84**
## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

### CODE REVIEW

**Comment by joerg84** [comment]
No strong feeling, but feels more consistent.

**Comment by joel-hamill** [comment]
@joerg84 this content is owned by product and any changes to it must be reviewed by product (Yrieix).

**Comment by joerg84** [comment]
@karlkfi could you review this? I don't have a gh handle of yrieix...

**Comment by joel-hamill** [comment]
@joerg84 i have messaged yrieix directly.

**Comment by joel-hamill** [comment]
@joerg84 talked to yrieix and he does not approve of this change. this content is going to be reworked in the near future by product. thanks.

**Pull request closed without merging**
