### PR TITLE
Addresses DOCS-2033, correct some small typos and tidy up grammar

### PR DESCRIPTION
**Pull request by mattj-io**
## Description
https://jira.mesosphere.com/browse/DOCS-2033

## Urgency
- [ ] Blocker 
- [ ] High
- [ x] Medium

## Requirements
- Test all commands and procedures.
- Build content [locally](https://github.com/dcos/dcos-docs#test-local) and test for formatting/links.
- Add redirects to [dcos-website/redirect-files](https://github.com/dcos/dcos-website#managing-redirects).
- Change all affected versions (e.g. 1.7, 1.8, and 1.9).
- See the [contribution guidelines](https://github.com/dcos/dcos-docs#contributing).

Addresses DOCS-2033, also fix some further numbering typos, and tidy up grammar. Make commands tested on MacOS and Ubuntu Linux for correctness, markdown tested locally in MacDown.

### CODE REVIEW

**Comment by sascala** [comment]
Thank you for the corrections, @mattj-io ! I redid the numbering -- markdown will automatically create correct numbering if every item on the list is numbered `1.`, so if you add new steps later, you don't need to go through and renumber.

**Comment by sascala** [comment]
You know, it is! But it’s because the code snippets and stuff aren’t indented. I love markdown.

**Comment by mattj-io** [comment]
I'll have a fiddle with it tomorrow and see if I can get it to render correctly.

**Comment by sascala** [comment]
I fixed it already.

**Pull request merged**
