### PR TITLE
Added dcos-gce documentation

### PR DESCRIPTION
**Pull request by ajazam**
As per Thomas Rampelbergs request I've created this pull request to add the documentation for dcos-gce to your website github repository. Apologies if it's in the wrong place.

### CODE REVIEW

**Comment by pyronicide** [comment]
@joel-hamill mind doing an edit pass when you get a chance?

**Comment by joel-hamill** [comment]
@pyronicide i put this on my calendar for today.

**Comment by joel-hamill** [comment]
Edit here: https://github.com/dcos/dcos-docs/pull/424.

**Comment by pyronicide** [comment]
@ajazam just merged this! It'll be live in a couple hours. Thank you for the contribution!!

**Comment by ajazam** [comment]
No problem. I only scratched my own itch.
On Fri, 8 Jul 2016 at 15:53, Thomas Rampelberg <notifications@github.com>
wrote:

> @ajazam <https://github.com/ajazam> just merged this! It'll be live in a
> couple hours. Thank you for the contribution!!
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dcos/dcos-docs/pull/421#issuecomment-231378900>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABwTc3mg3Dp1Q4cW9O3uZiHTfzgzRIONks5qTmKMgaJpZM4JDxCJ>
> .
>
-- 
Regards

Abdul Jabbar Azam
twitter: @ajazam

**Pull request merged**
