### PR TITLE
Commented out info about the Jobs CLI

### PR DESCRIPTION
**Pull request by sascala**
Note: I can't do a local build of the `/1.8` directory, so I can't test if the text I commented out actually disappears.

### CODE REVIEW

**Comment by joel-hamill** [comment]
@sascala did you test the output of this locally? looks a bit off for me: https://cl.ly/1U121b1u2w0q

**Comment by sascala** [comment]
I can't. `/1.8/` isn't "latest," so I can't do a local build

**Comment by sascala** [comment]
I removed the mentions of the CLI commands entirely. I can't view the local build ATM, but I can double check everything when the page is live.

**Comment by joel-hamill** [comment]
@sascala please fix the merge conflicts

**Comment by sascala** [comment]
there's some kind of unresolvable merge conflict here. Closing to redo.

**Pull request closed without merging**
