### PR TITLE
Azure

### PR DESCRIPTION
**Pull request by squillace**

### CODE REVIEW

**Comment by squillace** [comment]
@mhausenblas @pyronicide this was supposed to have merged two days ago, but didn't. I think it had to do with the modification of the repo from private to public; in any case, if it meets the minbar, please merge. I shall be augmenting this throughout the month with technical details.

**Comment by mhausenblas** [comment]
@squillace sorry, I was travelling back to Europe and largely offline. LGTM besides one thing I'd like you to fix: can you please add a `nav_title: Reference Implementation ACS`?

**Comment by mhausenblas** [comment]
This is #211

**Comment by squillace** [comment]
@mhausenblas I believe I've done so. Go for it!

**Pull request merged**
