### PR TITLE
Added pre-upgrade check to masters section

### PR DESCRIPTION
**Pull request by hanken**
I think, I today ran into the problem that I upgraded a cluster that was not stable in the beginning. To avoid other users run into the same I added a little pre-upgrade check to the masters section. 

I am not sure if this is true before the upgrade: 
"Verify that curl http://<dcos_master_private_ip>:5050/metrics/snapshot has the metric registrar/log/recovered with a value of 1 for each master."

## What type of changes does your doc introduce?
- [ ] Bug fix
- [ ] New feature 

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [x] Medium

## I have completed these items:
- [ ] I have tested all commands and code snippets.
- [ ] I have built locally and tested for broken links and formatting.
- [ ] I have made this change for all affected versions (e.g. 1.7, 1.8, and 1.9).
- [ ] My doc follows the style guide: https://github.com/dcos/dcos-docs#contributing.

Ping `@emanic`, `@sascala`, or `@joel-hamill` for reviewing pull request changes.

## If you included a comment with your commit, it appears here:

### CODE REVIEW

**Comment by joel-hamill** [comment]
@branden please review

**Comment by joel-hamill** [comment]
ping @hanken ^

**Comment by joerg84** [comment]
@hanken are you still on this?

**Comment by sascala** [comment]
I will add this text to the other upgrade docs in a separate PR

**Pull request merged**
