### PR TITLE
Feature/add api docs

### PR DESCRIPTION
**Pull request by daveyheuser**
## What are your changes?
Added support for docs api with swagger-ui. This PR is related to this one in DCOS-website https://github.com/dcos/dcos-website/pull/1008.

## What type of changes does your doc introduce?
- [ ] Bug fix
- [ ] New feature 

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [ ] Medium

## I have completed these items:
- [ ] I have tested all commands and code snippets.
- [ ] I have built locally and tested for broken links and formatting.
- [ ] I have made this change for all affected versions (e.g. 1.7, 1.8, and 1.9).
- [ ] My doc follows the style guide: https://github.com/dcos/dcos-docs#contributing.

Ping `@emanic`, `@sascala`, or `@joel-hamill` for reviewing pull request changes.

### CODE REVIEW

**Comment by daveyheuser** [comment]
I wasn't able to find a `develop` branch in this repo so it made the PR for the master, is this correct?

**Comment by ashenden** [comment]
@daveyheuser @joel-hamill you guys should sync on how to roll this out.  I know `master` is pretty sacred with regards to what ends up on the site, so if you want to just keep working in this branch until you're ready to roll it out on the site, that may be for the best.

@joel-hamill you should try this out on your machine.  If you want to come by my desk, I'll show you how to run the dcos-site locally and switch to this docs branch for preview.

**Comment by joel-hamill** [comment]
Related https://github.com/dcos/dcos-website/pull/1008

**Comment by joel-hamill** [comment]
I will add actual OSS API docs

**Comment by karlkfi** [comment]
A commit from this PR (which isn't in master) somehow ended up as the submodue sha in dcos-website in this commit: https://github.com/dcos/dcos-website/commit/fcd26a54155c44458e85ab558f4a3d759ce96286

This has broken the dcos-website develop branch deploy.

**Comment by karlkfi** [comment]
These changes were reverted from dcos-website develop branch: https://github.com/dcos/dcos-website/commit/2e209d7ef2d2987f01074fa9d1b482dea8d88462

**Pull request closed without merging**
