### PR TITLE
Remove minuteman 1.9 ports

### PR DESCRIPTION
**Pull request by joel-hamill**
## What are your changes?
- Related https://github.com/mesosphere/dcos-docs-enterprise/pull/1060
## What type of changes does your doc introduce?
- [x] Bug fix
- [ ] New feature 

## What is the urgency level of this change?
- [ ] Blocker
- [ ] High
- [x] Medium

## I have completed these items:
- [ ] I have tested all commands and code snippets.
- [ ] I have built locally and tested for broken links and formatting.
- [ ] I have made this change for all affected versions (e.g. 1.7, 1.8, and 1.9).
- [ ] My doc follows the style guide: https://github.com/dcos/dcos-docs#contributing.

Ping `@emanic`, `@sascala`, or `@joel-hamill` for reviewing pull request changes.

## If you included a comment with your commit, it appears here:

### CODE REVIEW

**Comment by joel-hamill** [comment]
Related https://github.com/mesosphere/dcos-docs-enterprise/pull/912#issuecomment-275739486

**Comment by linben** [comment]
confirmed that VXLAN port used is UDP 8472 (for navstar overlay networks)

**Comment by GoelDeepak** [comment]
I think the comment that triggered this change is mis-interpretated. The original comment was about ports required on a VIP which is not the same as port required on agent/master IP. 

What we should change, instead, is to take out minuteman from 1.9 as it has been merged into navstar

**Comment by joel-hamill** [comment]
@GoelDeepak okay, i have made the suggested changes

**Comment by emanic** [comment]
@joel-hamill some conflicts.

**Comment by joel-hamill** [comment]
@emanic conflicts fixed. thanks.

**Pull request merged**
