### PR TITLE
Do not allow any filtering

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by jgarcia-mesosphere** [comment]
LGTM (let's go to market) with this. I endorse these changes for CE.

**Comment by sargun** [comment]
@mhausenblas

**Comment by sargun** [comment]
@pyronicide

**Comment by pyronicide** [comment]
This needs some love still. @sargun 

We need to list TCP, UDP and ICMP to make sure folks understand what "unfettered" actually means.

**Pull request merged**
