### PR TITLE
added full path to support sharing with enterprise

### PR DESCRIPTION
**Pull request by joel-hamill**
@karlkfi can we make an exception for this particular link?

### CODE REVIEW

**Comment by karlkfi** [comment]
Why? This will break dev.dcos.io

**Comment by joel-hamill** [comment]
@karlkfi so we can reuse this topic here: https://docs.mesosphere.com/1.7/administration/installing/local/. alternatively we could remove from the enterprise doc (which might make sense).

**Comment by karlkfi** [comment]
Long term, I'd like to see a /releases on mesosphere.com that provides links to the Enterprise downloads. Then the public change logs can go there and the download links can just be password protected.

**Comment by joel-hamill** [comment]
@karlkfi what is dev.dcos.io used for? Staging?

**Comment by karlkfi** [comment]
Yes. It's for verifying that changes to the website look correct before promoting them to production.

**Comment by joel-hamill** [comment]
okay, i will stop sharing this topic, and update the link on enterprise.

**Pull request closed without merging**
