### PR TITLE
Moves usermgt page into id-and-access-mgt section; moves opt-out inst…

### PR DESCRIPTION
**Pull request by emanic**
…ructions for telemetry into telemetry topic; deletes opt-out.md as it is unnecessary and the auth section inside is redundant with opt-out instructions already in managing-auth topic; also adds sentence about upgrade option for opt-out in managing auth.

### CODE REVIEW

**Comment by pyronicide** [comment]
I need a separate opt-out page and this is missing all the required redirects.

**Comment by emanic** [comment]
Why do you need a separate opt-out page?

**Comment by pyronicide** [comment]
To link users to, so that they know exactly how to opt-out without anything else on the page.

**Comment by joel-hamill** [comment]
@pyronicide can you be more specific? from an information architecture perspective it's a bit odd to have Opt-Out on the same heading level/importance as Logging or Installation.

**Comment by pyronicide** [comment]
Some users care about everything they can turn off (and want to). Note that this refactor looses information (it doesn't tell how to opt-out of auth and doesn't include the redirects to make sure all the product links continue to work).

**Comment by emanic** [comment]
Just to clarify, it does not lose any information. Actually, the content was repeated in https://dcos.io/docs/1.7/administration/id-and-access-mgt/managing-authentication/ So, this actually removes a redundancy.

**Comment by joel-hamill** [comment]
Closing. These PRs duplicate effort: https://github.com/dcos/dcos-docs/pull/479 and https://github.com/dcos/dcos-docs/pull/560

**Pull request closed without merging**
