### PR TITLE
added telemetry info

### PR DESCRIPTION
**Pull request by joel-hamill**

### CODE REVIEW

**Comment by joel-hamill** [comment]
@pyronicide please review

**Comment by pyronicide** [comment]
Were we going to put the payloads in?

**Comment by joel-hamill** [comment]
ping @malnick ^

**Comment by pyronicide** [comment]
@malnick I'd like to see examples of what we're sending to segment in json format.

**Comment by malnick** [comment]
That's what @joel-hamill has in this PR

**Comment by joel-hamill** [comment]
@pyronicide are you asking us to specifically format in JSON? i took the raw JSON details and formatted into the human-readable table.

**Comment by pyronicide** [comment]
@joel-hamill I don't see the details? The table looks just like a summary?

**Comment by joel-hamill** [comment]
@pyronicide the table contains a row for each piece of data that we collect. However, it is not the actual JSON key name. Is that what you are asking (e.g. `Allocated disk space in MB` is `"disk_used"` in JSON). Is that what you want shown in the table?

**Comment by pyronicide** [comment]
I'd like the actual JSON responses instead of summaries or tables.

**Comment by joel-hamill** [comment]
@pyronicide are customers going to see this actual JSON output, or is this just what's sent back to us?

**Comment by pyronicide** [comment]
It is what gets sent back to us.

**Comment by joel-hamill** [comment]
@pyronicide take a look at the revisions ^

**Comment by pyronicide** [comment]
I still prefer the raw json. This is good enough for now though.

**Pull request merged**
