### PR TITLE
Added link to list of time zones to jobs doc

### PR DESCRIPTION
**Pull request by sascala**
@pierlo-upitup Is this what you were thinking?

### CODE REVIEW

**Comment by pierlo-upitup** [comment]
Thanks @sascala – how about adding one line to explain the cron format supported by metronome? Afaik there are some [variations](https://en.wikipedia.org/wiki/Cron#CRON_expression), and as a user I'd find great value in being told which format is supported.

@aquamatthias which library is metronome using to parse these strings? Maybe we can take it from there.

**Comment by sascala** [comment]
@aquamatthias Do you happen to know which cron format Metronome supports?

**Comment by aquamatthias** [comment]
@sascala We support the standard 5 element cron expression:
(minute hour dayOfMonth month dayOfWeek)

We also support an optional year at the end:
(minute hour dayOfMonth month dayOfWeek, year)

See https://github.com/dcos/metronome/blob/master/jobs/src/main/scala/dcos/metronome/model/CronSpec.scala#L32

**Comment by emanic** [comment]
LGTM

**Pull request merged**
