### PR TITLE
use --remote-name when downloading dcos binary.

### PR DESCRIPTION
**Pull request by orsenthil**
I tried the `curl` command suggested in the docs and the binary was streamed to my console. Better to suggest `curl --remote-name` to the customer so that they can download the binary.

### CODE REVIEW

**Comment by joel-hamill** [comment]
@tamarrow what do you think?

**Comment by tamarrow** [comment]
The previous UI instructions use `-O`, lets keep that to be consistent. We should also add this to the mac section

**Comment by orsenthil** [comment]
So, the change suggested is to use `-O` instead of `--remote-name` ?  I will update.

**Comment by joel-hamill** [comment]
thanks!

**Pull request merged**
